FROM node:lts-alpine as base

FROM base as build-stage
WORKDIR /build
COPY package*.json ./
COPY . .
RUN npm install -g pnpm && pnpm i && pnpm run build

FROM nginx:stable-alpine
COPY --from=build-stage /build/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
