//哪些指标显示单位
export const unitDatas={
    '单位时间内流动性净流入':true,
    '累计流动性资金':true,
    '单位时间内流动性添加总量':true,
    '单位时间内流动性撤出总量':true,
    '单位时间内资金净流入':true,
    '单位时间内主动买入':true,
    '单位时间内主动卖出':true,
    '交易额趋势':true
}
export const analysisConfig=[
    {title:'流动性分析',des:'展示选定币种/交易对在单位时间内的流动性净流入，计算方法为单位时间内的流。'},
    {title:'交易数据分析',des:'展示选定币种/交易对在单位时间内的流动性净流入，计算方法为单位时间内的流。'}
]
export const chartDataConfig=[
    {
        title:'资金净流入分析',
        desc:'展示选定币种/交易对在单位时间内的流动性净流入，计算方法为单位时间内的流。',
        flow:{
            id:0,
            tokenCofig:{
                usdCoin:true,
            },
            pairCofig:{
                usdCoin:false
            }
        },
        pay:{
            id:5,
            tokenCofig:{
                usdCoin:true,
            },
            pairCofig:{
                usdCoin:true
            }
        }
    },
    {
        title:'资金的流入流出明细分析',
        desc:'展示选定币种/交易对在单位时间内的流动性净流入，计算方法为单位时间内的流。',
        flow:{
            id:1,
            tokenCofig:{
                usdCoin:true,
            },
            pairCofig:{
                usdCoin:false
            }
        },
        pay:{
            id:6,
            tokenCofig:{
                usdCoin:true,
            },
            pairCofig:{
                usdCoin:true
            }
        }

    },
    {
        title:'频率数据分析',
        desc:'展示选定币种/交易对在单位时间内的流动性净流入，计算方法为单位时间内的流。',
        flow:{
            id:4,
            tokenCofig:{
                usdCoin:false,
            },
            pairCofig:{
                usdCoin:false
            }
        },
        pay:{
            id:9,
            tokenCofig:{
                usdCoin:false,
            },
            pairCofig:{
                usdCoin:false
            }
        }
    },
    {
        title:'新增参与人数分析（之前从未参与）',
        desc:'展示选定币种/交易对在单位时间内的流动性净流入，计算方法为单位时间内的流。',
        flow:{
            id:3,
            tokenCofig:{
                usdCoin:false,
            },
            pairCofig:{
                usdCoin:false
            }
        },
        pay:{
            id:8,
            tokenCofig:{
                usdCoin:false,
            },
            pairCofig:{
                usdCoin:false
            }
        }
    },
    {
        title:'参与人数分析',
        desc:'展示选定币种/交易对在单位时间内的流动性净流入，计算方法为单位时间内的流。',
        flow:{
            id:2,
            tokenCofig:{
                usdCoin:false,
            },
            pairCofig:{
                usdCoin:false
            }
        },
        pay:{
            id:7,
            tokenCofig:{
                usdCoin:false,
            },
            pairCofig:{
                usdCoin:false
            }
        }
    }
]