export default{
    title:'DeFi Farm APY List',
    apply:'Apply',
    platDes:'{chain} public chains, {project} projects, {pool} pools, the most comprehensive collection, support for cross-chain comparison, historical trends, APP reminder',
    allChain:'All',
    chain:'Chain',
    loanListChain:'Chain',
    searchTxt:'Search',
    search:'Search',
    notice:'Announcement',
    tutorial:'Tutorial',
    selectPlat:'choose platform',
    selectCoin:'choose token',
    playType:{
        plat:{
            title:'I have selected platform',
            des1:'Invest coin with the',
            high:'highest',
            des2:'APY'
        },
        coin:{
            title:'I have coins',
            des1:'platform with the',
            high:'highest',
            des2:'APY'
        },
        loan:{
            title:'I want to borrow',
            des1:'platform with the',
            high:'lowest',
            des2:'APY'
        }
    },
    my:'Favorite',
    total:'Total',
    single:'Single',
    more:'Load more',
    miningChartTitle:'单币挖矿收益率',
    loanChartTitle:'单币借贷利率',
    chainType:'Chain',
    poolType:'Type',
    poolTag:'Tag',
    apyGroup:'Total APY',
    singleInterest:'Single Interest',
    compoundInterest:'Compound Interest',
    remainRatio:'Remaining ratio',
    hasMoney:'Remaining',
    remainHasMoney:'Remaining',
    farm:'Farm',
    viewChart:'Chart',
    viewToken:'View Token',
    searchAll:'Search coin/project',
    project:'Project',
    projectTutorial:'Tutorial',
    comLink:'Link',
    pools:'Pools',
    tokens:'Tokens',
    highApy:'Highest APY',
    ok:'Ok',
    moreToken:'More Token',
    selectCoins:'Select other coins',
    farmApyList:'Farm APY List',
    loanList:'借贷利率榜',
    calculator:'calculator',
    lever:'杠杆倍数',
    projects:'Projects',
    all:'All',
    singleCoin:'SingleCoin',
    operate:'Operate',
    loanCoin:'借出币',
    borrowMoney:'可借金额',
    borrowAmount:'可借额度',
    interestGroup:'利率构成',
    loanListDes:'抵押借贷最佳路径',
    plat:'Platform'
}
