export default{
    title:'DeFi Farm APY List',
    apply:'Apply',
    miningTitle:'DeFi Farm APY List',
    loanTitle:'Find High-quality Farming Pool APR',
    platDes:'{chain} public chains, {project} projects, {pool} pools, the most comprehensive collection, support for cross-chain comparison, historical trends, APP reminder',
    allChain:'All',
    chain:'Chain',
    loanListChain:'Chain',
    searchTxt:'Search',
    search:'Search',
    notice:'Announcement',
    tutorial:'Tutorial',
    selectPlat:'choose platform',
    selectCoin:'choose token',
    playType:{
        plat:{
            title:'I have selected project',
            des1:'Invest token with the',
            high:'highest',
            des2:'APY'
        },
        coin:{
            title:'I have tokens',
            des1:'Project with the',
            high:'highest',
            des2:'APY'
        },
        loan:{
            title:'I want to borrow',
            des1:'Project with the',
            high:'lowest',
            des2:'APY'
        }
    },
    my:'Favorite',
    total:'Compound APY',
    single:'Token APR',
    more:'Load more',
    miningChartTitle:'Token Farm APY',
    loanChartTitle:'Token Borrow APY',
    chainType:'Chain',
    poolType:'Type',
    poolTag:'Tag',
    apyGroup:'APY Info',
    singleInterest:'Token APR',
    compoundInterest:'Compound APY',
    remainRatio:'Remaining',
    hasMoney:'Remaining',
    remainHasMoney:'Remaining',
    miningFarm:'Deposit',
    lendFarm:'Borrow',
    viewChart:'Chart',
    viewToken:'View Token',
    searchAll:'Search token/project',
    project:'Project',
    projectTutorial:'Tutorial',
    comLink:'Link',
    pools:'Pools',
    tokens:'Token',
    highApy:'Highest APY',
    ok:'OK',
    moreToken:'More Tokens',
    selectCoins:'Other tokens',
    farmApyList:'Farm APY List',
    loanList:'Borrow APY List',
    realCalculator:'Real Borrow APR calculator',
    calculator:'Calculator',
    lever:'Margin',
    projects:'Projects',
    all:'All',
    singleCoin:'Token',
    operate:'Operate',
    loanCoin:'Borrow',
    borrowMoney:'Liquidity',
    borrowAmount:'Liquidity',
    interestGroup:'APY Info',
    loanListDes:'The best way to borrow',
    plat:'Project',
    mortgage:'Supply APY',
    borrowApy:'Borrow APR',
    borrowNumber:'Borrow Remaining',
    cost:'True Cost',
    projectTvl:'TVL(Multi-chain)',
    userMoney:'User Revenue(Multi-chain)',
    supprotChain:'Supproted Chain',
    poolNumber:'Pools',
    projectView:'Project Overview',
    addPool:'Add Pools',
    unaudited:'Unaudited',
    dayUser:'Daily Active Users',
    projectRevenue:'Project Revenue',
    platCoinPrice:'Platform Token Price',
    sameProjectData:'Relative Projects Data',
    loanRouter:'The best way to borrow {value}',
    lowestLtv:'Lowest LTV',
    clearRatio:'Liquidation Ratio',
    mortgageInterest:'Supply APY',
    rankCompare:'Ranking comparison',
    trend:'Trending',
    trendCompare:'Trending comparison',
    poolCompare:'Pools comparison',
    relatedLoanTrend:'Related Loan Indicator Trending',
    loanTopBest:'{value} XXX Borrowing TOP 5 Borrow APR comparison',
    unitTiao:'',
    projectDes:'Introduction',
    timeFormat:'YYYY-M-DD',
    miningPool:'Farm Pools',
    loanPool:'Borrow Pools',
    projectData:'Project Data',
    selectedPool:'Selected Pools',
    allMiningPool:'All Farm Pools',
    allLoanPool:'All Borrow Pools',
    addLoanPool:'Add Borrow Pools',
    projectLook:{
        userMoney:'User Revenue',
        borrowMoney:'Borrowed',
        intoMoney:'Deposited',
        poolNumber:'Pools',
        singlePoolNumber:'Token Pools',
        lpPoolNumber:'LP Pools',
        unit:''
    },
    addProject:'Add Projects',
    selectedProject:'Selected Project',
    loanMoneyCoin:'Token',
    loanApr:'Borrow APR',
    loanPlat:'Project',
    pleaseSelect:'Select',
    diyaCoin:'Supply Token',
    diyaRato:'LTV',
    jiechuCoin:'Borrow Token',
    jiekuanMoney:'Cost',
    nowRato:'Current LTV',
    noLow:'No less than',
    realRato:'Borrow APR',
    clearData:'Reset',
    loanAllRouter:'All best ways to borrow',
    warning:'Waring',
    description: '',
    warningDes:'Risk warning: the data of this station comes from the public data of various platforms. The safety audit of the included contents is not conducted in this station, and the contents do not constitute investment suggestions. Please pay attention to the risks.'
}