export default{
    title:'DeFi Farm APY List',
    apply:'Apply',
    miningTitle:'DeFi Farm APY List',
    loanTitle:'发现优质矿池 APR',
    platDes:'{chain} public chains, {project} projects, {pool} pools, the most comprehensive collection, support for cross-chain comparison, historical trends, APP reminder',
    allChain:'All',
    chain:'Chain',
    loanListChain:'Chain',
    searchTxt:'Search',
    search:'Search',
    notice:'Announcement',
    tutorial:'Tutorial',
    selectPlat:'choose platform',
    selectCoin:'choose token',
    playType:{
        plat:{
            title:'I have selected platform',
            des1:'Invest coin with the',
            high:'highest',
            des2:'APY'
        },
        coin:{
            title:'I have coins',
            des1:'platform with the',
            high:'highest',
            des2:'APY'
        },
        loan:{
            title:'I want to borrow',
            des1:'platform with the',
            high:'lowest',
            des2:'APY'
        }
    },
    my:'Favorite',
    total:'Total',
    single:'Single',
    more:'Load more',
    miningChartTitle:'单币挖矿收益率',
    loanChartTitle:'单币借贷利率',
    chainType:'Chain',
    poolType:'Type',
    poolTag:'Tag',
    apyGroup:'Total APY',
    singleInterest:'Single Interest',
    compoundInterest:'Compound Interest',
    remainRatio:'Remaining ratio',
    hasMoney:'Remaining',
    remainHasMoney:'Remaining',
    farm:'Farm',
    viewChart:'Chart',
    viewToken:'View Token',
    searchAll:'Search coin/project',
    project:'Project',
    projectTutorial:'Tutorial',
    comLink:'Link',
    pools:'Pools',
    tokens:'Tokens',
    highApy:'Highest APY',
    ok:'Ok',
    moreToken:'More Token',
    selectCoins:'Select other coins',
    farmApyList:'Farm APY List',
    loanList:'借贷利率榜',
    calculator:'Calculator',
    lever:'Margin',
    projects:'Projects',
    all:'All',
    singleCoin:'SingleCoin',
    operate:'Operate',
    loanCoin:'借出币',
    borrowMoney:'可借金额',
    borrowAmount:'可借额度',
    interestGroup:'利率构成',
    loanListDes:'抵押借贷最佳路径',
    plat:'Platform',
    mortgage:'Mortgage Interest',
    borrowApy:'Borrow APY',
    borrowNumber:'Borrow Remaining',
    cost:'True cost',
    projectTvl:'TVL(Multi-chain)',
    userMoney:'User Revenue(Multi-chain)',
    supprotChain:'Supproted Chain',
    poolNumber:'Pools',
    projectView:'Project overview',
    addPool:'Add pools',
    unaudited:'Unaudited',
    dayUser:'Daily users',
    projectRevenue:'Project revenue',
    platCoinPrice:'Platform coin price',
    sameProjectData:'Similar project data',
    loanRouter:'The best way to borrow {value}',
    lowestLtv:'Lowest LTV Ratio',
    clearRatio:'Liquidation Ratio',
    mortgageInterest:'Mortgage interest',
    rankCompare:'Ranking comparison',
    trend:'Trend',
    trendCompare:'Trend comparison',
    poolCompare:'Pool comparison',
    relatedLoanTrend:'Related loan indicator trend',
    loanTopBest:'{value} borrowing TOP5 best APY comparison',
    unitTiao:'条',
    projectDes:'项目描述',
    timeFormat:'YYYY-M-DD',
    miningPool:'挖矿池子',
    loanPool:'借贷池子',
    projectData:'项目数据',
    selectedPool:'已选矿池',
    allMiningPool:'所有挖矿池子',
    allLoanPool:'所有借贷池子',
    addLoanPool:'添加借贷池子',
    projectLook:{
        userMoney:'用户总收益',
        borrowMoney:'借款总额',
        intoMoney:'存款总额',
        poolNumber:'总池子数',
        singlePoolNumber:'单币池子数',
        lpPoolNumber:'LP池子数',
        unit:'个'
    },
    addProject:'添加项目',
    selectedProject:'已选项目',
    loanMoneyCoin:'借款币种',
    loanApr:'借款APR'
}
