export default{
    title:'DeFi 挖矿APY大全',
    apply:'申请收录',
    platDes:'{chain} 条公链，{project} 个项目，{pool} 个池子，收录最全，支持跨链对比，历史趋势，APP 提醒',
    allChain:'全部公链',
    chain:'选择公链',
    search:'搜索币种',
    notice:'公告',
    tutorial:'教程',
    selectPlat:'选择平台',
    selectCoin:'选择币种',
    playType:{
        plat:{
            title:'我已选定平台',
            des1:'去投',
            high:'收益最高',
            des2:'的币种'
        },
        coin:{
            title:'我有币',
            des1:'去选择',
            high:'收益最高',
            des2:'的平台'
        },
        loan:{
            title:'我要借款',
            des1:'去选择',
            high:'利息最低',
            des2:'的币种'
        }
    },
    my:'自选',
    total:'综合',
    single:'单利',
    more:'加载更多',
    chainType:'公链类型',
    poolType:'矿池类型',
    poolTag:'矿池标签',
    apyGroup:'APY构成',
    singleInterest:'单利收益',
    compoundInterest:'复利收益',
    remainRatio:'剩余额度',
    hasMoney:'可投额度',
    remainHasMoney:'剩余可投额度',
    farm:'去挖矿',
    viewToken:'查看币种',
    searchAll:'搜索币种/项目',
    project:'项目名称',
    projectTutorial:'项目教程',
    comLink:'访问官网',
    pools:'池子',
    tokens:'币种',
    highApy:'最高 APY',
    ok:'确定',
    moreToken:'更多币种',
    selectCoins:'选择其他币种',
    farmApyList:'挖矿收益榜单',
    calculator:'真实利率计算器',
    lever:'杠杆倍数'

}
