<script lang="ts" setup>
import * as R from 'ramda'

const data={
  "data":{
    "lhbPriceContract":{
      "originalContractCallContext":{
        "reference":"lhbPriceContract",
        "contractAddress":"0x023f375a51Af8645D7446ba5942BAeDc53B0582D",
        "abi":[
          {
            "anonymous":false,
            "inputs":[
              {
                "indexed":true,
                "internalType":"address",
                "name":"owner",
                "type":"address"
              },
              {
                "indexed":true,
                "internalType":"address",
                "name":"spender",
                "type":"address"
              },
              {
                "indexed":false,
                "internalType":"uint256",
                "name":"value",
                "type":"uint256"
              }
            ],
            "name":"Approval",
            "type":"event"
          },
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"address",
                "name":"spender",
                "type":"address"
              },
              {
                "internalType":"uint256",
                "name":"value",
                "type":"uint256"
              }
            ],
            "name":"approve",
            "outputs":[
              {
                "internalType":"bool",
                "name":"",
                "type":"bool"
              }
            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function"
          },
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"address",
                "name":"to",
                "type":"address"
              }
            ],
            "name":"burn",
            "outputs":[
              {
                "internalType":"uint256",
                "name":"amount0",
                "type":"uint256"
              },
              {
                "internalType":"uint256",
                "name":"amount1",
                "type":"uint256"
              }
            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function"
          },
          {
            "anonymous":false,
            "inputs":[
              {
                "indexed":true,
                "internalType":"address",
                "name":"sender",
                "type":"address"
              },
              {
                "indexed":false,
                "internalType":"uint256",
                "name":"amount0",
                "type":"uint256"
              },
              {
                "indexed":false,
                "internalType":"uint256",
                "name":"amount1",
                "type":"uint256"
              },
              {
                "indexed":true,
                "internalType":"address",
                "name":"to",
                "type":"address"
              }
            ],
            "name":"Burn",
            "type":"event"
          },
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"address",
                "name":"",
                "type":"address"
              },
              {
                "internalType":"address",
                "name":"",
                "type":"address"
              }
            ],
            "name":"initialize",
            "outputs":[ ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function"
          },
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"address",
                "name":"to",
                "type":"address"
              }
            ],
            "name":"mint",
            "outputs":[
              {
                "internalType":"uint256",
                "name":"liquidity",
                "type":"uint256"
              }
            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function"
          },
          {
            "anonymous":false,
            "inputs":[
              {
                "indexed":true,
                "internalType":"address",
                "name":"sender",
                "type":"address"
              },
              {
                "indexed":false,
                "internalType":"uint256",
                "name":"amount0",
                "type":"uint256"
              },
              {
                "indexed":false,
                "internalType":"uint256",
                "name":"amount1",
                "type":"uint256"
              }
            ],
            "name":"Mint",
            "type":"event"
          },
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"address",
                "name":"owner",
                "type":"address"
              },
              {
                "internalType":"address",
                "name":"spender",
                "type":"address"
              },
              {
                "internalType":"uint256",
                "name":"value",
                "type":"uint256"
              },
              {
                "internalType":"uint256",
                "name":"deadline",
                "type":"uint256"
              },
              {
                "internalType":"uint8",
                "name":"v",
                "type":"uint8"
              },
              {
                "internalType":"bytes32",
                "name":"r",
                "type":"bytes32"
              },
              {
                "internalType":"bytes32",
                "name":"s",
                "type":"bytes32"
              }
            ],
            "name":"permit",
            "outputs":[ ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function"
          },
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"address",
                "name":"to",
                "type":"address"
              }
            ],
            "name":"skim",
            "outputs":[ ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function"
          },
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"uint256",
                "name":"amount0Out",
                "type":"uint256"
              },
              {
                "internalType":"uint256",
                "name":"amount1Out",
                "type":"uint256"
              },
              {
                "internalType":"address",
                "name":"to",
                "type":"address"
              },
              {
                "internalType":"bytes",
                "name":"data",
                "type":"bytes"
              }
            ],
            "name":"swap",
            "outputs":[ ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function"
          },
          {
            "anonymous":false,
            "inputs":[
              {
                "indexed":true,
                "internalType":"address",
                "name":"sender",
                "type":"address"
              },
              {
                "indexed":false,
                "internalType":"uint256",
                "name":"amount0In",
                "type":"uint256"
              },
              {
                "indexed":false,
                "internalType":"uint256",
                "name":"amount1In",
                "type":"uint256"
              },
              {
                "indexed":false,
                "internalType":"uint256",
                "name":"amount0Out",
                "type":"uint256"
              },
              {
                "indexed":false,
                "internalType":"uint256",
                "name":"amount1Out",
                "type":"uint256"
              },
              {
                "indexed":true,
                "internalType":"address",
                "name":"to",
                "type":"address"
              }
            ],
            "name":"Swap",
            "type":"event"
          },
          {
            "constant":false,
            "inputs":[ ],
            "name":"sync",
            "outputs":[ ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function"
          },
          {
            "anonymous":false,
            "inputs":[
              {
                "indexed":false,
                "internalType":"uint112",
                "name":"reserve0",
                "type":"uint112"
              },
              {
                "indexed":false,
                "internalType":"uint112",
                "name":"reserve1",
                "type":"uint112"
              }
            ],
            "name":"Sync",
            "type":"event"
          },
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"address",
                "name":"to",
                "type":"address"
              },
              {
                "internalType":"uint256",
                "name":"value",
                "type":"uint256"
              }
            ],
            "name":"transfer",
            "outputs":[
              {
                "internalType":"bool",
                "name":"",
                "type":"bool"
              }
            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function"
          },
          {
            "anonymous":false,
            "inputs":[
              {
                "indexed":true,
                "internalType":"address",
                "name":"from",
                "type":"address"
              },
              {
                "indexed":true,
                "internalType":"address",
                "name":"to",
                "type":"address"
              },
              {
                "indexed":false,
                "internalType":"uint256",
                "name":"value",
                "type":"uint256"
              }
            ],
            "name":"Transfer",
            "type":"event"
          },
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"address",
                "name":"from",
                "type":"address"
              },
              {
                "internalType":"address",
                "name":"to",
                "type":"address"
              },
              {
                "internalType":"uint256",
                "name":"value",
                "type":"uint256"
              }
            ],
            "name":"transferFrom",
            "outputs":[
              {
                "internalType":"bool",
                "name":"",
                "type":"bool"
              }
            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[
              {
                "internalType":"address",
                "name":"owner",
                "type":"address"
              },
              {
                "internalType":"address",
                "name":"spender",
                "type":"address"
              }
            ],
            "name":"allowance",
            "outputs":[
              {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[
              {
                "internalType":"address",
                "name":"owner",
                "type":"address"
              }
            ],
            "name":"balanceOf",
            "outputs":[
              {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[ ],
            "name":"decimals",
            "outputs":[
              {
                "internalType":"uint8",
                "name":"",
                "type":"uint8"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[ ],
            "name":"DOMAIN_SEPARATOR",
            "outputs":[
              {
                "internalType":"bytes32",
                "name":"",
                "type":"bytes32"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[ ],
            "name":"factory",
            "outputs":[
              {
                "internalType":"address",
                "name":"",
                "type":"address"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[ ],
            "name":"getReserves",
            "outputs":[
              {
                "internalType":"uint112",
                "name":"reserve0",
                "type":"uint112"
              },
              {
                "internalType":"uint112",
                "name":"reserve1",
                "type":"uint112"
              },
              {
                "internalType":"uint32",
                "name":"blockTimestampLast",
                "type":"uint32"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[ ],
            "name":"kLast",
            "outputs":[
              {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[ ],
            "name":"MINIMUM_LIQUIDITY",
            "outputs":[
              {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[ ],
            "name":"name",
            "outputs":[
              {
                "internalType":"string",
                "name":"",
                "type":"string"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[
              {
                "internalType":"address",
                "name":"owner",
                "type":"address"
              }
            ],
            "name":"nonces",
            "outputs":[
              {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[ ],
            "name":"PERMIT_TYPEHASH",
            "outputs":[
              {
                "internalType":"bytes32",
                "name":"",
                "type":"bytes32"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[
              {
                "internalType":"address",
                "name":"token",
                "type":"address"
              },
              {
                "internalType":"uint256",
                "name":"baseDecimal",
                "type":"uint256"
              }
            ],
            "name":"price",
            "outputs":[
              {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[ ],
            "name":"price0CumulativeLast",
            "outputs":[
              {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[ ],
            "name":"price1CumulativeLast",
            "outputs":[
              {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[ ],
            "name":"symbol",
            "outputs":[
              {
                "internalType":"string",
                "name":"",
                "type":"string"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[ ],
            "name":"token0",
            "outputs":[
              {
                "internalType":"address",
                "name":"",
                "type":"address"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[ ],
            "name":"token1",
            "outputs":[
              {
                "internalType":"address",
                "name":"",
                "type":"address"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[ ],
            "name":"totalSupply",
            "outputs":[
              {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          }
        ],
        "calls":[
          {
            "reference":"getLhbPric",
            "methodName":"price",
            "methodParameters":[
              "0x8F67854497218043E1f72908FFE38D0Ed7F24721",
              "1000000"
            ]
          }
        ]
      },
      "callsReturnContext":[
        {
          "returnValues":[
            {
              "type":"BigNumber",
              "hex":"0x010873"
            }
          ],
          "decoded":true,
          "reference":"getLhbPric",
          "methodName":"price",
          "methodParameters":[
            "0x8F67854497218043E1f72908FFE38D0Ed7F24721",
            "1000000"
          ],
          "success":true
        }
      ]
    },
    "calcLHBAPYsContract":{
      "originalContractCallContext":{
        "reference":"calcLHBAPYsContract",
        "contractAddress":"0x1a803cE05f6A95bAA58A65Eb81C14226A4d5b656",
        "abi":[
          {
            "constant":true,
            "inputs":[
              {
                "internalType":"contract CToken[]",
                "name":"cTokens",
                "type":"address[]"
              }
            ],
            "name":"calcLHBAPYs",
            "outputs":[
              {
                "components":[
                  {
                    "internalType":"address",
                    "name":"cToken",
                    "type":"address"
                  },
                  {
                    "internalType":"uint256",
                    "name":"supplyLHBAPY",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"borrowLHBAPY",
                    "type":"uint256"
                  }
                ],
                "internalType":"struct LendHubLensLHB.CTokenLHBData[]",
                "name":"",
                "type":"tuple[]"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          },
          {
            "constant":true,
            "inputs":[
              {
                "internalType":"contract CToken",
                "name":"cToken",
                "type":"address"
              }
            ],
            "name":"cTokenLHBMetadata",
            "outputs":[
              {
                "components":[
                  {
                    "internalType":"address",
                    "name":"cToken",
                    "type":"address"
                  },
                  {
                    "internalType":"uint256",
                    "name":"supplyLHBAPY",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"borrowLHBAPY",
                    "type":"uint256"
                  }
                ],
                "internalType":"struct LendHubLensLHB.CTokenLHBData",
                "name":"",
                "type":"tuple"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
          }
        ],
        "calls":[
          {
            "reference":"calcLHBAPYs0x99a2114B282acC9dd25804782ACb4D3a2b1Ad215",
            "methodName":"calcLHBAPYs",
            "methodParameters":[
              [
                "0x99a2114B282acC9dd25804782ACb4D3a2b1Ad215"
              ]
            ]
          },
          {
            "reference":"calcLHBAPYs0x1C478D5d1823D51c4c4b196652912A89D9b46c30",
            "methodName":"calcLHBAPYs",
            "methodParameters":[
              [
                "0x1C478D5d1823D51c4c4b196652912A89D9b46c30"
              ]
            ]
          },
          {
            "reference":"calcLHBAPYs0x1E5829E405654070cf4eaeFEA46d9a848A81462b",
            "methodName":"calcLHBAPYs",
            "methodParameters":[
              [
                "0x1E5829E405654070cf4eaeFEA46d9a848A81462b"
              ]
            ]
          },
          {
            "reference":"calcLHBAPYs0x505Bdd86108E7d9d662234F6a5F8A4CBAeCE81AB",
            "methodName":"calcLHBAPYs",
            "methodParameters":[
              [
                "0x505Bdd86108E7d9d662234F6a5F8A4CBAeCE81AB"
              ]
            ]
          },
          {
            "reference":"calcLHBAPYs0x6371531A3493466788179AEECe337d38117fa1ac",
            "methodName":"calcLHBAPYs",
            "methodParameters":[
              [
                "0x6371531A3493466788179AEECe337d38117fa1ac"
              ]
            ]
          },
          {
            "reference":"calcLHBAPYs0x276A4829d41Bfc3885eDB60c7B008188f096b082",
            "methodName":"calcLHBAPYs",
            "methodParameters":[
              [
                "0x276A4829d41Bfc3885eDB60c7B008188f096b082"
              ]
            ]
          },
          {
            "reference":"calcLHBAPYs0xd0dab69b6fb781805b4236867cF2A3D998BDF2EA",
            "methodName":"calcLHBAPYs",
            "methodParameters":[
              [
                "0xd0dab69b6fb781805b4236867cF2A3D998BDF2EA"
              ]
            ]
          },
          {
            "reference":"calcLHBAPYs0xc502F3f6f1b71CB7d856E70B574D27d942C2993C",
            "methodName":"calcLHBAPYs",
            "methodParameters":[
              [
                "0xc502F3f6f1b71CB7d856E70B574D27d942C2993C"
              ]
            ]
          },
          {
            "reference":"calcLHBAPYs0x96963ecfD541bc27F4Ca31299AF67D156A029C8b",
            "methodName":"calcLHBAPYs",
            "methodParameters":[
              [
                "0x96963ecfD541bc27F4Ca31299AF67D156A029C8b"
              ]
            ]
          },
          {
            "reference":"calcLHBAPYs0xE2Df9D182905B07c14dCAF824EF8465152Cb7169",
            "methodName":"calcLHBAPYs",
            "methodParameters":[
              [
                "0xE2Df9D182905B07c14dCAF824EF8465152Cb7169"
              ]
            ]
          },
          {
            "reference":"calcLHBAPYs0x6c4b0a4c19E0a842580dd116A306f297dc28cAC6",
            "methodName":"calcLHBAPYs",
            "methodParameters":[
              [
                "0x6c4b0a4c19E0a842580dd116A306f297dc28cAC6"
              ]
            ]
          },
          {
            "reference":"calcLHBAPYs0xD92F6c1Bb3296E4A2aDaaD56fdD8eC499e0582bb",
            "methodName":"calcLHBAPYs",
            "methodParameters":[
              [
                "0xD92F6c1Bb3296E4A2aDaaD56fdD8eC499e0582bb"
              ]
            ]
          },
          {
            "reference":"calcLHBAPYs0x0b3f6F8B72011F9Af56bfF9cd785633cC3BbEf18",
            "methodName":"calcLHBAPYs",
            "methodParameters":[
              [
                "0x0b3f6F8B72011F9Af56bfF9cd785633cC3BbEf18"
              ]
            ]
          },
          {
            "reference":"calcLHBAPYs0x0d37214e9A4B6E1AE3bA664bac3A6f0cbDa06665",
            "methodName":"calcLHBAPYs",
            "methodParameters":[
              [
                "0x0d37214e9A4B6E1AE3bA664bac3A6f0cbDa06665"
              ]
            ]
          },
          {
            "reference":"calcLHBAPYs0xEf4bBD27C75674A7c562d0d02E79415587c1595C",
            "methodName":"calcLHBAPYs",
            "methodParameters":[
              [
                "0xEf4bBD27C75674A7c562d0d02E79415587c1595C"
              ]
            ]
          }
        ]
      },
      "callsReturnContext":[
        {
          "returnValues":[
            [
              "0x99a2114B282acC9dd25804782ACb4D3a2b1Ad215",
              {
                "type":"BigNumber",
                "hex":"0x6133"
              },
              {
                "type":"BigNumber",
                "hex":"0x6436"
              }
            ]
          ],
          "decoded":true,
          "reference":"calcLHBAPYs0x99a2114B282acC9dd25804782ACb4D3a2b1Ad215",
          "methodName":"calcLHBAPYs",
          "methodParameters":[
            [
              "0x99a2114B282acC9dd25804782ACb4D3a2b1Ad215"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x1C478D5d1823D51c4c4b196652912A89D9b46c30",
              {
                "type":"BigNumber",
                "hex":"0x6377"
              },
              {
                "type":"BigNumber",
                "hex":"0x01027c"
              }
            ]
          ],
          "decoded":true,
          "reference":"calcLHBAPYs0x1C478D5d1823D51c4c4b196652912A89D9b46c30",
          "methodName":"calcLHBAPYs",
          "methodParameters":[
            [
              "0x1C478D5d1823D51c4c4b196652912A89D9b46c30"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x1E5829E405654070cf4eaeFEA46d9a848A81462b",
              {
                "type":"BigNumber",
                "hex":"0x2604"
              },
              {
                "type":"BigNumber",
                "hex":"0xfcb6"
              }
            ]
          ],
          "decoded":true,
          "reference":"calcLHBAPYs0x1E5829E405654070cf4eaeFEA46d9a848A81462b",
          "methodName":"calcLHBAPYs",
          "methodParameters":[
            [
              "0x1E5829E405654070cf4eaeFEA46d9a848A81462b"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x505Bdd86108E7d9d662234F6a5F8A4CBAeCE81AB",
              {
                "type":"BigNumber",
                "hex":"0x3acf"
              },
              {
                "type":"BigNumber",
                "hex":"0x014572"
              }
            ]
          ],
          "decoded":true,
          "reference":"calcLHBAPYs0x505Bdd86108E7d9d662234F6a5F8A4CBAeCE81AB",
          "methodName":"calcLHBAPYs",
          "methodParameters":[
            [
              "0x505Bdd86108E7d9d662234F6a5F8A4CBAeCE81AB"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x6371531A3493466788179AEECe337d38117fa1ac",
              {
                "type":"BigNumber",
                "hex":"0x1580"
              },
              {
                "type":"BigNumber",
                "hex":"0xd8c9"
              }
            ]
          ],
          "decoded":true,
          "reference":"calcLHBAPYs0x6371531A3493466788179AEECe337d38117fa1ac",
          "methodName":"calcLHBAPYs",
          "methodParameters":[
            [
              "0x6371531A3493466788179AEECe337d38117fa1ac"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x276A4829d41Bfc3885eDB60c7B008188f096b082",
              {
                "type":"BigNumber",
                "hex":"0x2104"
              },
              {
                "type":"BigNumber",
                "hex":"0xf681"
              }
            ]
          ],
          "decoded":true,
          "reference":"calcLHBAPYs0x276A4829d41Bfc3885eDB60c7B008188f096b082",
          "methodName":"calcLHBAPYs",
          "methodParameters":[
            [
              "0x276A4829d41Bfc3885eDB60c7B008188f096b082"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0xd0dab69b6fb781805b4236867cF2A3D998BDF2EA",
              {
                "type":"BigNumber",
                "hex":"0x2085"
              },
              {
                "type":"BigNumber",
                "hex":"0xc7b4"
              }
            ]
          ],
          "decoded":true,
          "reference":"calcLHBAPYs0xd0dab69b6fb781805b4236867cF2A3D998BDF2EA",
          "methodName":"calcLHBAPYs",
          "methodParameters":[
            [
              "0xd0dab69b6fb781805b4236867cF2A3D998BDF2EA"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0xc502F3f6f1b71CB7d856E70B574D27d942C2993C",
              {
                "type":"BigNumber",
                "hex":"0x5d7a"
              },
              {
                "type":"BigNumber",
                "hex":"0x0113fe"
              }
            ]
          ],
          "decoded":true,
          "reference":"calcLHBAPYs0xc502F3f6f1b71CB7d856E70B574D27d942C2993C",
          "methodName":"calcLHBAPYs",
          "methodParameters":[
            [
              "0xc502F3f6f1b71CB7d856E70B574D27d942C2993C"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x96963ecfD541bc27F4Ca31299AF67D156A029C8b",
              {
                "type":"BigNumber",
                "hex":"0x1d2f"
              },
              {
                "type":"BigNumber",
                "hex":"0xd964"
              }
            ]
          ],
          "decoded":true,
          "reference":"calcLHBAPYs0x96963ecfD541bc27F4Ca31299AF67D156A029C8b",
          "methodName":"calcLHBAPYs",
          "methodParameters":[
            [
              "0x96963ecfD541bc27F4Ca31299AF67D156A029C8b"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0xE2Df9D182905B07c14dCAF824EF8465152Cb7169",
              {
                "type":"BigNumber",
                "hex":"0x00"
              },
              {
                "type":"BigNumber",
                "hex":"0x00"
              }
            ]
          ],
          "decoded":true,
          "reference":"calcLHBAPYs0xE2Df9D182905B07c14dCAF824EF8465152Cb7169",
          "methodName":"calcLHBAPYs",
          "methodParameters":[
            [
              "0xE2Df9D182905B07c14dCAF824EF8465152Cb7169"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x6c4b0a4c19E0a842580dd116A306f297dc28cAC6",
              {
                "type":"BigNumber",
                "hex":"0x6f57"
              },
              {
                "type":"BigNumber",
                "hex":"0xc391"
              }
            ]
          ],
          "decoded":true,
          "reference":"calcLHBAPYs0x6c4b0a4c19E0a842580dd116A306f297dc28cAC6",
          "methodName":"calcLHBAPYs",
          "methodParameters":[
            [
              "0x6c4b0a4c19E0a842580dd116A306f297dc28cAC6"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0xD92F6c1Bb3296E4A2aDaaD56fdD8eC499e0582bb",
              {
                "type":"BigNumber",
                "hex":"0x0346"
              },
              {
                "type":"BigNumber",
                "hex":"0xa5b6"
              }
            ]
          ],
          "decoded":true,
          "reference":"calcLHBAPYs0xD92F6c1Bb3296E4A2aDaaD56fdD8eC499e0582bb",
          "methodName":"calcLHBAPYs",
          "methodParameters":[
            [
              "0xD92F6c1Bb3296E4A2aDaaD56fdD8eC499e0582bb"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x0b3f6F8B72011F9Af56bfF9cd785633cC3BbEf18",
              {
                "type":"BigNumber",
                "hex":"0x0d5e"
              },
              {
                "type":"BigNumber",
                "hex":"0x8563"
              }
            ]
          ],
          "decoded":true,
          "reference":"calcLHBAPYs0x0b3f6F8B72011F9Af56bfF9cd785633cC3BbEf18",
          "methodName":"calcLHBAPYs",
          "methodParameters":[
            [
              "0x0b3f6F8B72011F9Af56bfF9cd785633cC3BbEf18"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x0d37214e9A4B6E1AE3bA664bac3A6f0cbDa06665",
              {
                "type":"BigNumber",
                "hex":"0x0b1e"
              },
              {
                "type":"BigNumber",
                "hex":"0xd597"
              }
            ]
          ],
          "decoded":true,
          "reference":"calcLHBAPYs0x0d37214e9A4B6E1AE3bA664bac3A6f0cbDa06665",
          "methodName":"calcLHBAPYs",
          "methodParameters":[
            [
              "0x0d37214e9A4B6E1AE3bA664bac3A6f0cbDa06665"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0xEf4bBD27C75674A7c562d0d02E79415587c1595C",
              {
                "type":"BigNumber",
                "hex":"0x3b0f"
              },
              {
                "type":"BigNumber",
                "hex":"0x017065"
              }
            ]
          ],
          "decoded":true,
          "reference":"calcLHBAPYs0xEf4bBD27C75674A7c562d0d02E79415587c1595C",
          "methodName":"calcLHBAPYs",
          "methodParameters":[
            [
              "0xEf4bBD27C75674A7c562d0d02E79415587c1595C"
            ]
          ],
          "success":true
        }
      ]
    },
    "pricesContract":{
      "originalContractCallContext":{
        "reference":"pricesContract",
        "contractAddress":"0xC2D598E05d3B36876bAc957A60018c6C22D17fb0",
        "abi":[
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"contract CToken",
                "name":"cToken",
                "type":"address"
              },
              {
                "internalType":"address payable",
                "name":"account",
                "type":"address"
              }
            ],
            "name":"cTokenBalances",
            "outputs":[
              {
                "components":[
                  {
                    "internalType":"address",
                    "name":"cToken",
                    "type":"address"
                  },
                  {
                    "internalType":"uint256",
                    "name":"balanceOf",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"borrowBalanceCurrent",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"balanceOfUnderlying",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"tokenBalance",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"tokenAllowance",
                    "type":"uint256"
                  }
                ],
                "internalType":"struct LendHubLens.CTokenBalances",
                "name":"",
                "type":"tuple"
              }
            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function",
            "signature":"0xbdf950c9"
          },
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"contract CToken[]",
                "name":"cTokens",
                "type":"address[]"
              },
              {
                "internalType":"address payable",
                "name":"account",
                "type":"address"
              }
            ],
            "name":"cTokenBalancesAll",
            "outputs":[
              {
                "components":[
                  {
                    "internalType":"address",
                    "name":"cToken",
                    "type":"address"
                  },
                  {
                    "internalType":"uint256",
                    "name":"balanceOf",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"borrowBalanceCurrent",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"balanceOfUnderlying",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"tokenBalance",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"tokenAllowance",
                    "type":"uint256"
                  }
                ],
                "internalType":"struct LendHubLens.CTokenBalances[]",
                "name":"",
                "type":"tuple[]"
              }
            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function",
            "signature":"0x0972bf8b"
          },
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"contract CToken",
                "name":"cToken",
                "type":"address"
              }
            ],
            "name":"cTokenMetadata",
            "outputs":[
              {
                "components":[
                  {
                    "internalType":"address",
                    "name":"cToken",
                    "type":"address"
                  },
                  {
                    "internalType":"uint256",
                    "name":"exchangeRateCurrent",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"supplyRatePerBlock",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"borrowRatePerBlock",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"reserveFactorMantissa",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"totalBorrows",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"totalReserves",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"totalSupply",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"totalCash",
                    "type":"uint256"
                  },
                  {
                    "internalType":"bool",
                    "name":"isListed",
                    "type":"bool"
                  },
                  {
                    "internalType":"uint256",
                    "name":"collateralFactorMantissa",
                    "type":"uint256"
                  },
                  {
                    "internalType":"address",
                    "name":"underlyingAssetAddress",
                    "type":"address"
                  },
                  {
                    "internalType":"uint256",
                    "name":"cTokenDecimals",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"underlyingDecimals",
                    "type":"uint256"
                  }
                ],
                "internalType":"struct LendHubLens.CTokenMetadata",
                "name":"",
                "type":"tuple"
              }
            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function",
            "signature":"0x158eca8b"
          },
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"contract CToken[]",
                "name":"cTokens",
                "type":"address[]"
              }
            ],
            "name":"cTokenMetadataAll",
            "outputs":[
              {
                "components":[
                  {
                    "internalType":"address",
                    "name":"cToken",
                    "type":"address"
                  },
                  {
                    "internalType":"uint256",
                    "name":"exchangeRateCurrent",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"supplyRatePerBlock",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"borrowRatePerBlock",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"reserveFactorMantissa",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"totalBorrows",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"totalReserves",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"totalSupply",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"totalCash",
                    "type":"uint256"
                  },
                  {
                    "internalType":"bool",
                    "name":"isListed",
                    "type":"bool"
                  },
                  {
                    "internalType":"uint256",
                    "name":"collateralFactorMantissa",
                    "type":"uint256"
                  },
                  {
                    "internalType":"address",
                    "name":"underlyingAssetAddress",
                    "type":"address"
                  },
                  {
                    "internalType":"uint256",
                    "name":"cTokenDecimals",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"underlyingDecimals",
                    "type":"uint256"
                  }
                ],
                "internalType":"struct LendHubLens.CTokenMetadata[]",
                "name":"",
                "type":"tuple[]"
              }
            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function",
            "signature":"0x4b70d84b"
          },
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"contract CToken",
                "name":"cToken",
                "type":"address"
              }
            ],
            "name":"cTokenUnderlyingPrice",
            "outputs":[
              {
                "components":[
                  {
                    "internalType":"address",
                    "name":"cToken",
                    "type":"address"
                  },
                  {
                    "internalType":"uint256",
                    "name":"underlyingPrice",
                    "type":"uint256"
                  }
                ],
                "internalType":"struct LendHubLens.CTokenUnderlyingPrice",
                "name":"",
                "type":"tuple"
              }
            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function",
            "signature":"0xc5ae5934"
          },
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"contract CToken[]",
                "name":"cTokens",
                "type":"address[]"
              }
            ],
            "name":"cTokenUnderlyingPriceAll",
            "outputs":[
              {
                "components":[
                  {
                    "internalType":"address",
                    "name":"cToken",
                    "type":"address"
                  },
                  {
                    "internalType":"uint256",
                    "name":"underlyingPrice",
                    "type":"uint256"
                  }
                ],
                "internalType":"struct LendHubLens.CTokenUnderlyingPrice[]",
                "name":"",
                "type":"tuple[]"
              }
            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function",
            "signature":"0x2b2d5ed6"
          },
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"contract ComptrollerLensInterface",
                "name":"comptroller",
                "type":"address"
              },
              {
                "internalType":"address",
                "name":"account",
                "type":"address"
              }
            ],
            "name":"getAccountLimits",
            "outputs":[
              {
                "components":[
                  {
                    "internalType":"contract CToken[]",
                    "name":"markets",
                    "type":"address[]"
                  },
                  {
                    "internalType":"uint256",
                    "name":"liquidity",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"shortfall",
                    "type":"uint256"
                  }
                ],
                "internalType":"struct LendHubLens.AccountLimits",
                "name":"",
                "type":"tuple"
              }
            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function",
            "signature":"0x7dd8f6d9"
          },
          {
            "constant":true,
            "inputs":[
              {
                "internalType":"contract LendHub",
                "name":"lhb",
                "type":"address"
              },
              {
                "internalType":"address",
                "name":"account",
                "type":"address"
              }
            ],
            "name":"getCompBalanceMetadata",
            "outputs":[
              {
                "components":[
                  {
                    "internalType":"uint256",
                    "name":"balance",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"votes",
                    "type":"uint256"
                  },
                  {
                    "internalType":"address",
                    "name":"delegate",
                    "type":"address"
                  }
                ],
                "internalType":"struct LendHubLens.CompBalanceMetadata",
                "name":"",
                "type":"tuple"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function",
            "signature":"0x416405d7"
          },
          {
            "constant":false,
            "inputs":[
              {
                "internalType":"contract LendHub",
                "name":"lhb",
                "type":"address"
              },
              {
                "internalType":"contract ComptrollerLensInterface",
                "name":"comptroller",
                "type":"address"
              },
              {
                "internalType":"address",
                "name":"account",
                "type":"address"
              }
            ],
            "name":"getCompBalanceMetadataExt",
            "outputs":[
              {
                "components":[
                  {
                    "internalType":"uint256",
                    "name":"balance",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"votes",
                    "type":"uint256"
                  },
                  {
                    "internalType":"address",
                    "name":"delegate",
                    "type":"address"
                  },
                  {
                    "internalType":"uint256",
                    "name":"allocated",
                    "type":"uint256"
                  }
                ],
                "internalType":"struct LendHubLens.CompBalanceMetadataExt",
                "name":"",
                "type":"tuple"
              }
            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function",
            "signature":"0x1ea63741"
          },
          {
            "constant":true,
            "inputs":[
              {
                "internalType":"contract LendHub",
                "name":"lhb",
                "type":"address"
              },
              {
                "internalType":"address",
                "name":"account",
                "type":"address"
              },
              {
                "internalType":"uint32[]",
                "name":"blockNumbers",
                "type":"uint32[]"
              }
            ],
            "name":"getCompVotes",
            "outputs":[
              {
                "components":[
                  {
                    "internalType":"uint256",
                    "name":"blockNumber",
                    "type":"uint256"
                  },
                  {
                    "internalType":"uint256",
                    "name":"votes",
                    "type":"uint256"
                  }
                ],
                "internalType":"struct LendHubLens.CompVotes[]",
                "name":"",
                "type":"tuple[]"
              }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function",
            "signature":"0x59564219"
          }
        ],
        "calls":[
          {
            "reference":"cTokenUnderlyingPriceAll0x99a2114B282acC9dd25804782ACb4D3a2b1Ad215",
            "methodName":"cTokenUnderlyingPriceAll",
            "methodParameters":[
              [
                "0x99a2114B282acC9dd25804782ACb4D3a2b1Ad215"
              ]
            ]
          },
          {
            "reference":"cTokenUnderlyingPriceAll0x1C478D5d1823D51c4c4b196652912A89D9b46c30",
            "methodName":"cTokenUnderlyingPriceAll",
            "methodParameters":[
              [
                "0x1C478D5d1823D51c4c4b196652912A89D9b46c30"
              ]
            ]
          },
          {
            "reference":"cTokenUnderlyingPriceAll0x1E5829E405654070cf4eaeFEA46d9a848A81462b",
            "methodName":"cTokenUnderlyingPriceAll",
            "methodParameters":[
              [
                "0x1E5829E405654070cf4eaeFEA46d9a848A81462b"
              ]
            ]
          },
          {
            "reference":"cTokenUnderlyingPriceAll0x505Bdd86108E7d9d662234F6a5F8A4CBAeCE81AB",
            "methodName":"cTokenUnderlyingPriceAll",
            "methodParameters":[
              [
                "0x505Bdd86108E7d9d662234F6a5F8A4CBAeCE81AB"
              ]
            ]
          },
          {
            "reference":"cTokenUnderlyingPriceAll0x6371531A3493466788179AEECe337d38117fa1ac",
            "methodName":"cTokenUnderlyingPriceAll",
            "methodParameters":[
              [
                "0x6371531A3493466788179AEECe337d38117fa1ac"
              ]
            ]
          },
          {
            "reference":"cTokenUnderlyingPriceAll0x276A4829d41Bfc3885eDB60c7B008188f096b082",
            "methodName":"cTokenUnderlyingPriceAll",
            "methodParameters":[
              [
                "0x276A4829d41Bfc3885eDB60c7B008188f096b082"
              ]
            ]
          },
          {
            "reference":"cTokenUnderlyingPriceAll0xd0dab69b6fb781805b4236867cF2A3D998BDF2EA",
            "methodName":"cTokenUnderlyingPriceAll",
            "methodParameters":[
              [
                "0xd0dab69b6fb781805b4236867cF2A3D998BDF2EA"
              ]
            ]
          },
          {
            "reference":"cTokenUnderlyingPriceAll0xc502F3f6f1b71CB7d856E70B574D27d942C2993C",
            "methodName":"cTokenUnderlyingPriceAll",
            "methodParameters":[
              [
                "0xc502F3f6f1b71CB7d856E70B574D27d942C2993C"
              ]
            ]
          },
          {
            "reference":"cTokenUnderlyingPriceAll0x96963ecfD541bc27F4Ca31299AF67D156A029C8b",
            "methodName":"cTokenUnderlyingPriceAll",
            "methodParameters":[
              [
                "0x96963ecfD541bc27F4Ca31299AF67D156A029C8b"
              ]
            ]
          },
          {
            "reference":"cTokenUnderlyingPriceAll0xE2Df9D182905B07c14dCAF824EF8465152Cb7169",
            "methodName":"cTokenUnderlyingPriceAll",
            "methodParameters":[
              [
                "0xE2Df9D182905B07c14dCAF824EF8465152Cb7169"
              ]
            ]
          },
          {
            "reference":"cTokenUnderlyingPriceAll0x6c4b0a4c19E0a842580dd116A306f297dc28cAC6",
            "methodName":"cTokenUnderlyingPriceAll",
            "methodParameters":[
              [
                "0x6c4b0a4c19E0a842580dd116A306f297dc28cAC6"
              ]
            ]
          },
          {
            "reference":"cTokenUnderlyingPriceAll0xD92F6c1Bb3296E4A2aDaaD56fdD8eC499e0582bb",
            "methodName":"cTokenUnderlyingPriceAll",
            "methodParameters":[
              [
                "0xD92F6c1Bb3296E4A2aDaaD56fdD8eC499e0582bb"
              ]
            ]
          },
          {
            "reference":"cTokenUnderlyingPriceAll0x0b3f6F8B72011F9Af56bfF9cd785633cC3BbEf18",
            "methodName":"cTokenUnderlyingPriceAll",
            "methodParameters":[
              [
                "0x0b3f6F8B72011F9Af56bfF9cd785633cC3BbEf18"
              ]
            ]
          },
          {
            "reference":"cTokenUnderlyingPriceAll0x0d37214e9A4B6E1AE3bA664bac3A6f0cbDa06665",
            "methodName":"cTokenUnderlyingPriceAll",
            "methodParameters":[
              [
                "0x0d37214e9A4B6E1AE3bA664bac3A6f0cbDa06665"
              ]
            ]
          },
          {
            "reference":"cTokenUnderlyingPriceAll0xEf4bBD27C75674A7c562d0d02E79415587c1595C",
            "methodName":"cTokenUnderlyingPriceAll",
            "methodParameters":[
              [
                "0xEf4bBD27C75674A7c562d0d02E79415587c1595C"
              ]
            ]
          }
        ]
      },
      "callsReturnContext":[
        {
          "returnValues":[
            [
              "0x99a2114B282acC9dd25804782ACb4D3a2b1Ad215",
              {
                "type":"BigNumber",
                "hex":"0xcd6cac"
              }
            ]
          ],
          "decoded":true,
          "reference":"cTokenUnderlyingPriceAll0x99a2114B282acC9dd25804782ACb4D3a2b1Ad215",
          "methodName":"cTokenUnderlyingPriceAll",
          "methodParameters":[
            [
              "0x99a2114B282acC9dd25804782ACb4D3a2b1Ad215"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x1C478D5d1823D51c4c4b196652912A89D9b46c30",
              {
                "type":"BigNumber",
                "hex":"0x2386f26fc10000"
              }
            ]
          ],
          "decoded":true,
          "reference":"cTokenUnderlyingPriceAll0x1C478D5d1823D51c4c4b196652912A89D9b46c30",
          "methodName":"cTokenUnderlyingPriceAll",
          "methodParameters":[
            [
              "0x1C478D5d1823D51c4c4b196652912A89D9b46c30"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x1E5829E405654070cf4eaeFEA46d9a848A81462b",
              {
                "type":"BigNumber",
                "hex":"0x0a541671b0"
              }
            ]
          ],
          "decoded":true,
          "reference":"cTokenUnderlyingPriceAll0x1E5829E405654070cf4eaeFEA46d9a848A81462b",
          "methodName":"cTokenUnderlyingPriceAll",
          "methodParameters":[
            [
              "0x1E5829E405654070cf4eaeFEA46d9a848A81462b"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x505Bdd86108E7d9d662234F6a5F8A4CBAeCE81AB",
              {
                "type":"BigNumber",
                "hex":"0xb2503180"
              }
            ]
          ],
          "decoded":true,
          "reference":"cTokenUnderlyingPriceAll0x505Bdd86108E7d9d662234F6a5F8A4CBAeCE81AB",
          "methodName":"cTokenUnderlyingPriceAll",
          "methodParameters":[
            [
              "0x505Bdd86108E7d9d662234F6a5F8A4CBAeCE81AB"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x6371531A3493466788179AEECe337d38117fa1ac",
              {
                "type":"BigNumber",
                "hex":"0x016c52cc"
              }
            ]
          ],
          "decoded":true,
          "reference":"cTokenUnderlyingPriceAll0x6371531A3493466788179AEECe337d38117fa1ac",
          "methodName":"cTokenUnderlyingPriceAll",
          "methodParameters":[
            [
              "0x6371531A3493466788179AEECe337d38117fa1ac"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x276A4829d41Bfc3885eDB60c7B008188f096b082",
              {
                "type":"BigNumber",
                "hex":"0x03fe8668"
              }
            ]
          ],
          "decoded":true,
          "reference":"cTokenUnderlyingPriceAll0x276A4829d41Bfc3885eDB60c7B008188f096b082",
          "methodName":"cTokenUnderlyingPriceAll",
          "methodParameters":[
            [
              "0x276A4829d41Bfc3885eDB60c7B008188f096b082"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0xd0dab69b6fb781805b4236867cF2A3D998BDF2EA",
              {
                "type":"BigNumber",
                "hex":"0x17c9"
              }
            ]
          ],
          "decoded":true,
          "reference":"cTokenUnderlyingPriceAll0xd0dab69b6fb781805b4236867cF2A3D998BDF2EA",
          "methodName":"cTokenUnderlyingPriceAll",
          "methodParameters":[
            [
              "0xd0dab69b6fb781805b4236867cF2A3D998BDF2EA"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0xc502F3f6f1b71CB7d856E70B574D27d942C2993C",
              {
                "type":"BigNumber",
                "hex":"0x0f4240"
              }
            ]
          ],
          "decoded":true,
          "reference":"cTokenUnderlyingPriceAll0xc502F3f6f1b71CB7d856E70B574D27d942C2993C",
          "methodName":"cTokenUnderlyingPriceAll",
          "methodParameters":[
            [
              "0xc502F3f6f1b71CB7d856E70B574D27d942C2993C"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x96963ecfD541bc27F4Ca31299AF67D156A029C8b",
              {
                "type":"BigNumber",
                "hex":"0x09f12a80"
              }
            ]
          ],
          "decoded":true,
          "reference":"cTokenUnderlyingPriceAll0x96963ecfD541bc27F4Ca31299AF67D156A029C8b",
          "methodName":"cTokenUnderlyingPriceAll",
          "methodParameters":[
            [
              "0x96963ecfD541bc27F4Ca31299AF67D156A029C8b"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0xE2Df9D182905B07c14dCAF824EF8465152Cb7169",
              {
                "type":"BigNumber",
                "hex":"0x02ba1754"
              }
            ]
          ],
          "decoded":true,
          "reference":"cTokenUnderlyingPriceAll0xE2Df9D182905B07c14dCAF824EF8465152Cb7169",
          "methodName":"cTokenUnderlyingPriceAll",
          "methodParameters":[
            [
              "0xE2Df9D182905B07c14dCAF824EF8465152Cb7169"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x6c4b0a4c19E0a842580dd116A306f297dc28cAC6",
              {
                "type":"BigNumber",
                "hex":"0x13ce50"
              }
            ]
          ],
          "decoded":true,
          "reference":"cTokenUnderlyingPriceAll0x6c4b0a4c19E0a842580dd116A306f297dc28cAC6",
          "methodName":"cTokenUnderlyingPriceAll",
          "methodParameters":[
            [
              "0x6c4b0a4c19E0a842580dd116A306f297dc28cAC6"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0xD92F6c1Bb3296E4A2aDaaD56fdD8eC499e0582bb",
              {
                "type":"BigNumber",
                "hex":"0x257589e0"
              }
            ]
          ],
          "decoded":true,
          "reference":"cTokenUnderlyingPriceAll0xD92F6c1Bb3296E4A2aDaaD56fdD8eC499e0582bb",
          "methodName":"cTokenUnderlyingPriceAll",
          "methodParameters":[
            [
              "0xD92F6c1Bb3296E4A2aDaaD56fdD8eC499e0582bb"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x0b3f6F8B72011F9Af56bfF9cd785633cC3BbEf18",
              {
                "type":"BigNumber",
                "hex":"0x018940a8"
              }
            ]
          ],
          "decoded":true,
          "reference":"cTokenUnderlyingPriceAll0x0b3f6F8B72011F9Af56bfF9cd785633cC3BbEf18",
          "methodName":"cTokenUnderlyingPriceAll",
          "methodParameters":[
            [
              "0x0b3f6F8B72011F9Af56bfF9cd785633cC3BbEf18"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0x0d37214e9A4B6E1AE3bA664bac3A6f0cbDa06665",
              {
                "type":"BigNumber",
                "hex":"0x196d8d50"
              }
            ]
          ],
          "decoded":true,
          "reference":"cTokenUnderlyingPriceAll0x0d37214e9A4B6E1AE3bA664bac3A6f0cbDa06665",
          "methodName":"cTokenUnderlyingPriceAll",
          "methodParameters":[
            [
              "0x0d37214e9A4B6E1AE3bA664bac3A6f0cbDa06665"
            ]
          ],
          "success":true
        },
        {
          "returnValues":[
            [
              "0xEf4bBD27C75674A7c562d0d02E79415587c1595C",
              {
                "type":"BigNumber",
                "hex":"0xb1396a50"
              }
            ]
          ],
          "decoded":true,
          "reference":"cTokenUnderlyingPriceAll0xEf4bBD27C75674A7c562d0d02E79415587c1595C",
          "methodName":"cTokenUnderlyingPriceAll",
          "methodParameters":[
            [
              "0xEf4bBD27C75674A7c562d0d02E79415587c1595C"
            ]
          ],
          "success":true
        }
      ]
    }
  },
  "statusCode":200
}
const d=data.data
const keys=R.keys(d)
// console.log(d)
// const s=R.map(item=>R.map(itemTwo=> ({[R.prop('reference',itemTwo)]:R.prop('returnValues',itemTwo)}), R.prop('callsReturnContext',item)),d)
// const result=R.mapObjIndexed((item,i)=>{
//   return {[keys[i]]:item}
// },s)
const dd=R.mapObjIndexed((item,i)=> R.mapObjIndexed((itemTwo,j)=> ({[R.prop('reference',itemTwo)]:R.prop('returnValues',itemTwo)}), R.prop('callsReturnContext',item)),d)
const result=R.mapObjIndexed((item,i)=> R.mapObjIndexed((itemTwo,j)=> ({[R.prop('reference',itemTwo)]:R.prop('returnValues',itemTwo)}), R.prop('callsReturnContext',item)),d)
console.log(R.mergeAll(dd))
// R.mapObjIndexed((item,i)=>{
// },s)
// console.log(s)
</script>
<template>

</template>
<style scoped>
.showY{
  @apply overFlow-hidden overFlow-y-scroll;
}
.selectedRow {
  @apply bg-global-primary bg-opacity-8 h-full flex items-center;
}

.openContainer {
  @apply  bg-global-primary bg-opacity-4;
}

.openHeader{
  @apply mb-2.5 font-kdFang  flex-1  text-kd14px18px text-global-highTitle;
}
.header {
  border-top: 1px solid rgba(37, 62, 111, 0.12);
  border-bottom: 1px solid rgba(37, 62, 111, 0.12);
}

.txtSmall {
  white-space: nowrap;
  text-overflow: ellipsis;
  overflow: hidden;
}


.showY::-webkit-scrollbar {
  height: 8px;
  @apply w-0.5;
}
.showY::-webkit-scrollbar-thumb:vertical {
  background: rgba(0, 0, 0, 0.1);
}
</style>
// @formatter:off
<route lang="yaml">
meta:
 layout: liquidityLayout
</route>
// @formatter:off
